name: ci
on: [push, pull_request]
jobs:
  ci_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install nm
        uses: sudo apt-get install -y binutils
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.2
      - name: Run unit tests
        run: make test
      - name: Run fonctionnal tests
        run: ./e2e.sh
