name: ci
on: [push, pull_request]
jobs:
  ci_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.2
      - name: Create file with no permission for testing
        run: touch test/bin/no_perm
      - name: Change permission to 000
        run: chmod 000 test/bin/no_perm
      - name: Run tests
        run: make test
