name: ci
on: [push, pull_request]
jobs:
  ci_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.2
      - name: Install make
        run: apt install -y make
      - name: Run tests
        run: make test
